# Generated by Django 5.2.7 on 2025-10-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_frequency",
            field=models.CharField(
                choices=[
                    ("immediate", "Immédiat"),
                    ("daily", "Quotidien"),
                    ("weekly", "Hebdomadaire"),
                    ("disabled", "Désactivé"),
                ],
                default="immediate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="push_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
