# Generated by Django 5.2.7 on 2025-10-21 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_user_email_notifications_user_fcm_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="news.news",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["news", "is_approved"],
                        name="news_commen_news_id_4fb10e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Créé"),
                            ("submitted", "Soumis pour modération"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                            ("edited", "Modifié"),
                            ("deleted", "Supprimé"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Raison de l'action (optionnel pour approbation)",
                    ),
                ),
                (
                    "previous_content",
                    models.TextField(
                        blank=True, help_text="Contenu avant modification"
                    ),
                ),
                (
                    "new_content",
                    models.TextField(
                        blank=True, help_text="Nouveau contenu après modification"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="news.news",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["news", "action"], name="news_modera_news_id_22ae92_idx"
                    ),
                    models.Index(
                        fields=["moderator", "timestamp"],
                        name="news_modera_moderat_4d1dc1_idx",
                    ),
                ],
            },
        ),
    ]
