# Generated by Django 5.2.7 on 2025-10-28 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_comment_moderationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True)),
                ("est_actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
                "ordering": ["faculte", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Faculte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True)),
                ("est_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Faculté",
                "verbose_name_plural": "Facultés",
                "ordering": ["universite", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        choices=[
                            ("admin_global", "Administrateur Global"),
                            ("moderateur", "Modérateur"),
                            ("enseignant", "Enseignant"),
                            ("publiant", "Publiant"),
                            ("etudiant", "Étudiant"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("permissions", models.JSONField(blank=True, default=dict)),
                ("est_actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Rôle",
                "verbose_name_plural": "Rôles",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Universite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("adresse", models.TextField(blank=True)),
                ("ville", models.CharField(blank=True, max_length=100)),
                ("pays", models.CharField(default="France", max_length=100)),
                ("site_web", models.URLField(blank=True)),
                ("est_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Université",
                "verbose_name_plural": "Universités",
                "ordering": ["nom"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="date_verification",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="motif_verification",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="promotion",
            field=models.CharField(
                blank=True, help_text="Ex: L1, L2, M1, M2...", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="utilisateurs_verifies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="utilisateurs",
                to="news.departement",
            ),
        ),
        migrations.AddField(
            model_name="departement",
            name="faculte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departements",
                to="news.faculte",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="faculte",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="utilisateurs",
                to="news.faculte",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nouveau_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="utilisateurs",
                to="news.role",
            ),
        ),
        migrations.AddField(
            model_name="faculte",
            name="universite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facultes",
                to="news.universite",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="universite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="utilisateurs",
                to="news.universite",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="departement",
            unique_together={("nom", "faculte")},
        ),
        migrations.AlterUniqueTogether(
            name="faculte",
            unique_together={("nom", "universite")},
        ),
    ]
