# Generated by Django 5.2.7 on 2025-11-04 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_add_organizational_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="content",
        ),
        migrations.RemoveField(
            model_name="news",
            name="title",
        ),
        migrations.AddField(
            model_name="news",
            name="admin_invalidated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="news_invalidated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Administrateur ayant invalidé",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="admin_invalidation_reason",
            field=models.TextField(
                blank=True, verbose_name="Motivation de l'invalidation"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="desired_publish_end",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Date de fin de publication souhaitée",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="desired_publish_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de publication souhaitée"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="draft_content",
            field=models.TextField(
                blank=True, default="", verbose_name="Contenu avant modération"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="draft_title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Titre avant modération",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="final_content",
            field=models.TextField(
                blank=True, default="", verbose_name="Contenu après modération"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="final_title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Titre après modération",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="invalidated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date d'invalidation"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="moderator_approved",
            field=models.BooleanField(
                default=False, verbose_name="Accord du modérateur"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="programme_ou_formation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Programme ou formation concerné par cette news",
                max_length=200,
                verbose_name="Programme ou formation destinataire",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="written_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de rédaction"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur (publiant)",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="news.category",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="expiry_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date d'expiration"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="importance",
            field=models.CharField(
                choices=[
                    ("low", "Faible"),
                    ("medium", "Moyenne"),
                    ("high", "Importante"),
                    ("urgent", "Urgente"),
                ],
                default="medium",
                max_length=20,
                verbose_name="Importance",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="moderated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de modération"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="moderation_comment",
            field=models.TextField(
                blank=True, verbose_name="Commentaire de modération"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="moderator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="news_moderated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modérateur",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="publish_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date effective de publication"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("pending", "En attente de modération"),
                    ("published", "Publié"),
                    ("rejected", "Rejeté"),
                    ("invalidated", "Invalidé"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="importance_threshold",
            field=models.CharField(
                choices=[
                    ("low", "Faible"),
                    ("medium", "Moyenne"),
                    ("high", "Importante"),
                    ("urgent", "Urgente"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
    ]
