# Generated by Django 5.2.7 on 2025-11-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_remove_news_content_remove_news_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="promotion",
            field=models.CharField(
                blank=True, help_text="Ex: L1, L2, M1, M2...", max_length=50
            ),
        ),
    ]
